default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV['ECOMMERCE_API_DATABASE_USER'] %>
  password: <%= ENV['ECOMMERCE_API_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_api_development

test:
  <<: *default
  database: ecommerce_api_test

production:
  <<: *default
  database: ecommerce_api_production
  username: <%= ENV['ECOMMERCE_API_DATABASE_USERNAME'] %>
  password: <%= ENV['ECOMMERCE_API_DATABASE_PASSWORD'] %>